JacksonRiver/springboard_modules

salesforce/salesforce_sync/includes/salesforce_sync.sync.inc, salesforce/salesforce_sync/salesforce_sync.info, salesforce/salesforce_sync/tests/salesforce_sync.sync.test, salesforce/salesforce_sync/tests/salesforce_sync.sync_truncate.test
Added some tests around string truncation and truncating html entities during SalesforceSync batch string truncation.
=> Salesforce sync batch item field string truncate test

fundraiser/modules/fundraiser_commerce/gateways/commerce_litle.inc, fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- Change the Litle orderSource for recurring credit card charges that are not the master donation.
=> Change the Litle orderSource for recurring charges

salesforce/salesforce_donation/salesforce_donation.module
With this line removed a properlly mapped 'Partially Refunded' stage will map correctly.
=> Remove hardcoded refunded status so Partially refunded status will sync.

fundraiser/modules/fundraiser_commerce/gateways/commerce_cybersource.inc, fundraiser/modules/fundraiser_commerce/gateways/commerce_cybersource/commerce_cybersource.module
This adds options for handling AVS decline, and fixes the cardonfile integration.
=> Cybersource Improved Cardonfile Handling and AVS Declines

fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Debugging code was left behind.
=> Remove watchdog debug.

springboard/modules/springboard_stats/springboard_stats.module
Implemented a cron queue for stats tallying, so stats queries and field data saves won't happen during donation processing.
=> Springboard Statistics asynchronous processing

fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.info, fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module, fundraiser/modules/fundraiser_sustainers/includes/schedules/sustainersBaseSchedule.inc, fundraiser/modules/fundraiser_sustainers/includes/schedules/sustainersMonthlySchedule.inc, fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers.test, fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers_eom.test, fundraiser/modules/fundraiser_upsell/fundraiser_upsell.module
This updates the end of month date algorithm so that a month with less days than the starting month will result in the charge hitting on the last day.
=> Sustainer End of Month Refactor

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
This change clears the value in the state field when the country field ajax refresh occurs.
=> Clear State Field Value on Country Select

springboard_tag/springboard_tag.module
Resolves an issue where the content type setting was not being evaluated correctly.
=> SB Tags Content Type Fix

fundraiser/js/donation_validation.js, fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
Validate the zip code for US only when US is the selected country.
=> Zip Code Validation for US Only

fundraiser/fundraiser.module
Add a currency symbol token to the other amount description, replace it on display of field. Add display callback for currency field.
=> Minimum Donation Currency Text not Responding to Currency

springboard/modules/springboard_admin/springboard_admin.module, springboard/modules/springboard_views/springboard_views.views_default.inc
This adds an admin setting to control which form types may display on the SB admin pages.
=> Hide Content Type on SB Admin Form Page

fundraiser/modules/fundraiser_sustainers/modules/fundraiser_date_mode/fundraiser_date_mode.module
In the date mode re-queue function fix code to work with $sustainer as value an array.
=> On Date Mode Enable Resolve Missing Index Errors

fundraiser/modules/fundraiser_tickets/components/tickets.inc, fundraiser/modules/fundraiser_tickets/fundraiser_tickets.info, fundraiser/modules/fundraiser_tickets/fundraiser_tickets.module, fundraiser/modules/fundraiser_tickets/includes/fundraiser_tickets.fields.inc, fundraiser/modules/fundraiser_tickets/js/fundraiser_tickets.js
- Uses the currency from the ticketed event node to display currency in the ticket boxes.
- Forces the same currency when created ticket types.
- Validates that the add-on donation form has the same currency as the ticketed event node.
=> 363 currency with fundraiser tickets

form_layouts/form_layouts.module, page_wrappers/page_wrappers.module
Updated form_layouts and page_wrappers modules to consolidate their node form settings into a single "Display settings" tab.
=> Consolidate node form settings for Form Layouts and Page Wrappers

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.info, fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
Address Field version 1.0 changed the addressfield_default_values() function, so this branch changes that implementation to pass the arguments the newest version of Address Field is looking for.
=> This updates the addressfield_default_values() for Address Field 1.0

springboard/modules/springboard_views/springboard_views.views_default.inc
Changes the views bid field to use the admin ui item report path.
=> Set Path on bid field to Admin UI Items Report Path

springboard/modules/springboard_admin/springboard_admin.module, springboard/modules/springboard_views/springboard_views.views_default.inc
Contains minor changes to Springboard Admin donation form lists.
=> UI Adjustments to Lists

fundraiser/fundraiser.admin.inc, fundraiser/fundraiser.api.inc, fundraiser/fundraiser.module, fundraiser/modules/fundraiser_webform/fundraiser_webform.module
The validation won't get triggered on an ajax submit.
Alternatively we could use triggering_element if submitted isn't appropriate.
=> Check if we're doing a form submit before doing donation form validation

form_layouts/form_layouts.module
We now initialize the template regions used in the form layouts template so that it will cope with non-existing fieldsets.
=> Change the form layouts preprocess to support ticketed events.

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
This adds a new status of Void available to commerce orders.
=> Add Void Status for Commerce Orders

fundraiser/modules/fundraiser_commerce/gateways/commerce_sage_payments.inc, fundraiser/modules/fundraiser_commerce/gateways/commerce_sage_payments/commerce_sage_payments.admin.inc, fundraiser/modules/fundraiser_commerce/gateways/commerce_sage_payments/commerce_sage_payments.module, fundraiser/modules/fundraiser_commerce/gateways/commerce_sage_payments/libraries/wsVaultVirtualCheck.xml
Adds EFT support and other improvements to the Sage gateway.
=> Sage EFT Support

fundraiser/modules/fundraiser_tickets/js/fundraiser_tickets.js
Fixes an issue where the ticket price calculations could not be performed on ticket prices > $999.
=> Remove commas from numbers so math can be performed.

springboard_advocacy/modules/sba_message_action/sba_message_action.module
Code to hide a node-type-specific field was living outside of node-type control structure
=> move test for show_my_name into control structure

springboard_advocacy/modules/sba_message_action/sba_message_action.module
Use default custom fail message by default...
=> use default custom confirmation if form ahs not been saved.

webform_user/webform_user.module
Replaces node tokens on webform component default value rendering for text based webform components.
=> Run token replace on some webform component default values.

fundraiser/modules/fundraiser_upsell/fundraiser_upsell.module
Assembla ticket no. 596, adding close button for Upsell preview in the Admin.
=> Adding admin close button for Upsell preview.

springboard/modules/springboard_views/springboard_views.views_default.inc
7.x-4.x-460-correct-donation-report-date-filter 
7.x-4.x-607-change-donations-report-sort-order
=> Merged changes of two related branches branches... 

springboard_token/README.txt, springboard_token/springboard_token.info, springboard_token/springboard_token.module
Removes extraneous token types and tokens from fundraiser-enabled nodes, and extraneous token types from message actions.
=> Token filtering hotfix

springboard_advocacy/modules/sba_message_action/sba_message_action.module
=> fix errant parenthesis in empty test

springboard_advocacy/modules/sba_message/sba_message.install, springboard_advocacy/modules/sba_message/sba_message.module, springboard_advocacy/modules/sba_message_action/includes/install/sba_message_action.install_fields.inc, springboard_advocacy/modules/sba_message_action/includes/sba_message_action.components.inc, springboard_advocacy/modules/sba_message_action/sba_message_action.info, springboard_advocacy/modules/sba_message_action/sba_message_action.install, springboard_advocacy/modules/sba_message_action/sba_message_action.module, springboard_advocacy/modules/springboard_target/includes/springboard_target.custom_targets.inc
Please let me know if doesn't work correctly.
=> #490: Updating language for advocacy

springboard_advocacy/modules/sba_message_action/includes/sba_message_action.downloads.inc, springboard_advocacy/modules/sba_message_action/templates/sba_message_action_downloads.tpl.php
=> 7.x 4.x 600 advocacy hold to failed messages

fundraiser/modules/fundraiser_commerce/gateways/commerce_sage_payments/commerce_sage_payments.module, fundraiser/modules/fundraiser_offline/fundraiser_offline.module
These are three cherry-picked commits that completed recent work regarding passing the email entered into the donation form, instead of the logged in user, to the relevant payment gateways.
=> Cs 288 7.x 4.x sage offline email

fundraiser/modules/fundraiser_upsell/modules/fundraiser_upsell_salesforce/fundraiser_upsell_salesforce.module
This change is required to allow upsell to work with either NPSP or luminate recurring donations.
=> Adding support for fundraiser_sustainers_series

fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.install, market_source/market_source.install, salesforce/salesforce_luminate/salesforce_luminate.install, salesforce/salesforce_npsp/salesforce_npsp.install
Misread some documentation and made this change last week. Didn't notice in testing that it wasn't working properly.
=> Reverted a breaking change to update hooks using batch API.

springboard_p2p/modules/springboard_p2p_campaign/springboard_p2p_campaign.features.field_instance.inc, springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.info, springboard_p2p/springboard_p2p.module
Merge outstanding PR 724 https://github.com/JacksonRiver/springboard_modules/pull/724.
=> Cs 27722 7.x 4.8.2.1 774053b p2p merge

springboard_advocacy/includes/views/springboard_advocacy.views_default.inc
Restore missing petition filter in view.
=> restore missing petition filter to actions view

springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Add message field validation to quicksign validate function
=> add validation check for required message fields to quicksign

springboard_advocacy/modules/sba_message_action/includes/sba_message_action.preview.inc, springboard_advocacy/modules/sba_social_action/includes/sba_social_action.preview.inc
Test for the existence of the editable submit button text needs to use empty, not isset, to prevent potentially blank buttons.
=> use empty instead of isset to test for value

salesforce/salesforce_genmap/salesforce_genmap.install
Fixes the SforcePartnerClient exception.
=> Added missing SF library to salesforce_gemap update hook.

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
....when they are in use on a donation form. Accomplished by disabling the submit button on the confirmation form and setting message(s) for the user to disable them on the donation form(s).
=> Prevents disabling of payment gateways 

salesforce/salesforce_log/includes/salesforce_log_handler_field_drupal_id.inc, springboard_advocacy/modules/sba_quicksign/sba_quicksign.module, springboard_advocacy/modules/sba_social_action/includes/sba_social_action.form.inc, webform_user/includes/webform_user.drush.inc, webform_user/js/webform_user.js, webform_user/tests/webform_user.config.test, webform_user/tests/webform_user.confirmation.test, webform_user/tests/webform_user.field_truncate.test, webform_user/tests/webform_user.submission.test, webform_user/tests/webform_user_test_setup.php, webform_user/webform_user.admin.inc, webform_user/webform_user.module
=> 7.x 4.x 878 webform user coding standards

salesforce/salesforce_log/includes/salesforce_log_handler_field_drupal_id.inc, springboard_advocacy/modules/sba_message_action/sba_message_action.module, springboard_advocacy/modules/sba_social_action/sba_social_action.module
add hook_page_wrappers_page_node_alter() to social actions.
Also fix typo in the same hook in message actions.
=> make pagewrappers work on social action previews

springboard_advocacy/modules/sba_social_action/includes/sba_social_action.preview.inc
Shuffle, rather than randomly select, alternative tweets to prevent random repeat of the same alternative.
=> 7.x 4.x 828 randomizing social

springboard_advocacy/springboard_advocacy.module
This is a reroll of an old branch/fix Dan R. had been working on.
=> show warning if no targets for message

springboard_advocacy/modules/sba_quicksign/js/sba_quicksign.js, springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Add click-once js, remove unused js.
=> quicksign click once

springboard_advocacy/modules/sba_social_action/includes/sba_social_action.form.inc
Fixes a php notice on social actions.
=> pass form by reference in social action validate

fundraiser/modules/fundraiser_tickets/fundraiser_tickets.module, fundraiser/modules/fundraiser_tickets/views/fundraiser_tickets.views.inc
Ready for review. This turned out to be a pretty small fix and it does appear to work, although it feels a little sketchy to me. Sort of like saying, "Well, this field is required on the add-on form but let's just ignore that for now."
=> Add-on Donation Autocomplete Not Working

springboard_advocacy/modules/sba_social_action/includes/sba_social_action.preview.inc
Test for existence needs to be more precise.
=> Fix test for auth requirement

fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module, fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/includes/install/fundraiser_sustainers_upgrade.install_example.inc
Add a sustainers upgrade node edit form token tree. Plus some token description updates.
=> 7.x 4.10 beta1 1015 tokens on node edit

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
The diff is ugly, but all this does is wrap everything in a `if ($form_state['op'] == 'disable')` so that gateways can be re-enabled.
=> Allow gateways in-use to be re-enabled.

fundraiser/modules/fundraiser_tickets/components/tickets.inc, fundraiser/modules/fundraiser_tickets/fundraiser_tickets.install, fundraiser/modules/fundraiser_tickets/includes/fundraiser_tickets.product.inc, fundraiser/modules/fundraiser_tickets/js/fundraiser_tickets.js, fundraiser/modules/fundraiser_webform/fundraiser_webform.module
Reroll of 7.x-4.10-beta1-735-remaining-ticket-count-override.
=> 7.x 4.x 735 remaining ticket count override reroll

market_source/js/market_source.js
Original branch was 7.x-4.10-rc2-1018-encrypted-search-referrals-break-sb-js
=> Added conditional checks to ensure matches and matches[2] are set.

fundraiser/modules/fundraiser_tickets/components/tickets.inc
Original branch was 7.x-4.10-rc2-1047-php-notice-on-auto-closed-ticketed-events.
=> Fixed save_value error when tickets are closed or soldout

fundraiser/modules/fundraiser_upsell/css/fundraiser_upsell.css, fundraiser/modules/fundraiser_upsell/fundraiser_upsell.module
Adding secondary modal close to upsell modals.
Assembla: https://www.assembla.com/spaces/springboard/tickets/312-upsell-modal----add---39-x--39--box-in-upper-right-to-close-modal-window/details
Depends on springboard-themes pull request: JacksonRiver/springboard-themes#24
Resurrection of https://github.com/JacksonRiver/springboard_modules/pull/1062
=> re #312 - adding close "x" to the upsell modal

fundraiser/modules/fundraiser_webform/fundraiser_webform.module
Adding field-specific classes to common fundraiser form elements
This is a replacement for the automatically closed pull request here: https://github.com/JacksonRiver/springboard_modules/pull/1063
=> 7.x 4.x 262 common fundraiser classes

springboard_advocacy/modules/springboard_petition/springboard_petition.install
Adds a default value for the petition internal name field on the petition example node.
=> add default value for petition internal name field

springboard_advocacy/modules/sba_message_action/includes/sba_message_action.reports.inc
=> fix undefined index notice on message acton report

fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
…ual-ask form uses a checkbox component for donation type.
=> #1121: zero dollar donations

fundraiser/fundraiser.module
Rolled against the 7.x-4.10.2 tag. Supercedes https://github.com/JacksonRiver/springboard_modules/pull/1095
=> #1106: Ask amount default value bug

springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc, springboard_advocacy/modules/sba_message_action/includes/sba_message_action.webform.inc, springboard_dw/springboard_dw.module
This pull request fixes php notices relating to undefined indexes in the data warehouse module, as well as corrects the advocacy success hooks with single and multi step action submissions.
=> 7.x 4.11.2 hotfix dw

springboard_advocacy/modules/sba_social_action/includes/install/sba_social_action.twitter_message_install.inc, springboard_advocacy/modules/springboard_target/includes/springboard_target.custom_targets.inc, springboard_p2p/modules/springboard_p2p_campaign/springboard_p2p_campaign.features.field_instance.inc, springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.features.field_instance.inc
This is my third attempt at this pull request. Please let me know if you see issues.
=> #204 - Updating YouTube Capitalization

fundraiser/modules/fundraiser_commerce/js/gateway-client-form.js
Try/Catch error suppression was masking an undefined variable error triggered when there is no submission help text (.fundraiser_submit_message) element.
Not sure why that control structure is in there.
=> 7.x 4.12 beta submit button text

springboard_advocacy/includes/views/plugins/springboard_advocacy_views_plugin_query.inc, springboard_advocacy/modules/sba_message_action/includes/sba_message_action.webform.inc
Adds a test for a sometime absent variable on line 552.  If a custom target does not have an organizational "title" a php notice would display.
Also slips in some code formatting corrections.
=> 7.x 4.12 beta 1379 missing var

fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Replace billing update form fields with a message for a series that was cancelled or expired.
=> t1279 no billing update for expired series

salesforce/salesforce_donation_history/salesforce_donation_history.install, salesforce/salesforce_donation_history/salesforce_donation_history.module
Missing required param StageName in default SOQL query and install config function.
=> fix default SOQL query and install form parameters

fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
This prior pull request:
https://github.com/JacksonRiver/springboard_modules/pull/1133
got partially regressed in 4.12-beta since being merged.
=> fix regressed omitted sustainer action

fundraiser/modules/fundraiser_quick_donate/includes/fundraiser_quick_donate.springboard_hmac.inc, springboard_hmac/springboard_hmac.info, springboard_hmac/springboard_hmac.module
t1495: Added Springboard cookie user ID check function springboard_hmac_verify_user_cookie() and implemented it for login-and-redirect and quick-donate actions.
=> t1495: Added Springboard cookie user ID check

fundraiser/modules/fundraiser_designations/components/designations.inc, fundraiser/modules/fundraiser_designations/fundraiser_designations.install, fundraiser/modules/fundraiser_designations/includes/fundraiser_designations.product.inc, fundraiser/modules/fundraiser_designations/includes/views/fundraiser_designations.views_default.inc, fundraiser/modules/fundraiser_designations/js/fundraiser_designations.js
Updating Fundraiser Designation product type to include an "internal title" field. Also updating the management view to display this new field.
=> 7.x 4.x designation update 50

salesforce/salesforce_donation_history/includes/salesforce_donation_history.pages.inc
https://app.assembla.com/spaces/springboard/tickets/1478/details?comment=1097369423
=> Changes pending donations message.

fundraiser/modules/fundraiser_designations/js/fundraiser_designations.js
Adds ability to aggregate multiple clock thru urls into designations cart and fixes a formatting issue which caused incorrect amounts to display in cart when total > $1000
=> allow aggregation of url params in designations cart

fundraiser/fundraiser.module, fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
to fundraiser_log_donation_processing() during IPN processing.
=> Make PayPal WPS donations log 

fundraiser/modules/fundraiser_ab/plugins/win_conditions/donations_highest_avg.inc, fundraiser/modules/fundraiser_ab/plugins/win_conditions/donations_highest_gross.inc, webform_ab/webform_ab.admin.inc, webform_ab/webform_ab.module
Prevent win conditions from becoming active to prior to any hits on a test.
=> 7.x 4.x webform ab start test

secure_prepopulate/secure_prepopulate.components.inc
Function had an incorrect wrong anti-cloning test.
=> don't clone autofilled field

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
Reset all countries variable to default to false
=> reset all countries variable to default to false

springboard_advocacy/modules/sba_message/js/sba_message.js, springboard_advocacy/modules/sba_message/sba_message.admin.inc, springboard_advocacy/modules/springboard_target/modules/sba_target_search/js/sba_target_search.js
Custom groups checkbox and title form was disappearing in some workflows.
=> Fix an issue with the save as custom group form disappearing

springboard_advocacy/modules/springboard_target/modules/sba_target_search/sba_target_search.module
Convert null values to an empty string on non-required fields.
=> check for null values when building custom targets

springboard_dw/modules/springboard_dw_queue_legacy/springboard_dw_queue_legacy.drush.inc
so extra_props gets populated.
=> Ensure all submission_data values are included

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module, fundraiser/modules/fundraiser_webform/fundraiser_webform.module, springboard_p2p/includes/springboard_p2p.register.inc, springboard_p2p/springboard_p2p.module
This PR pulls the 7.x 4.14.1 code into 7.x-4.x.
=> Merge 7.x 4.14.1 into 7.x-4.x

springboard_dw/modules/springboard_dw_queue_legacy/springboard_dw_queue_legacy.drush.inc
=> Keep mysql connection alive.

fundraiser/fundraiser.module
Checks that $payment_method_fields is an array, prior to attempting to merge it into the master array.
=> 1612 add test for array before merging payment method fields

webform_ui/js/remove-tabledrag.js
Fixes incorrect test for value of webform ui cookie which prevented the show/hide link from displaying properly on the webform components page.
=> fix webform ui cookie value check

email_wrappers/email_wrappers.module
This was lost in a merge conflict.
=> 1860 email bcc validation

market_source/modules/offline_market_source/offline-market-source.css, market_source/modules/offline_market_source/offline_market_source.info, market_source/modules/offline_market_source/offline_market_source.install, market_source/modules/offline_market_source/offline_market_source.module
This adds a submodule Offline Market Source that allows admins to be able to specify which market source fields are overrideable for offline donations
=> 249 Market Source submodule for allowing overrides for offline Donations.

fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module, springboard_p2p/includes/springboard_p2p.register.inc
Make sure p2p users get unqiue user names after registration.
=> 1696 make sure p2p users get unque names

fundraiser/modules/fundraiser_tickets/fundraiser_tickets.module
Publishcontent module was unpublishing ticketed events when the ticket settings page was saved. This removes publish content's influence from that page using the PC api hooks.
=> implement publish content hooks in tickets

braintree_integration/modules/braintree_applepay/braintree_applepay.module, braintree_integration/modules/braintree_payment/braintree_payment.module, email_wrappers/email_wrappers.module, fundraiser/fundraiser.module, fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module, fundraiser/modules/fundraiser_commerce/gateways/commerce_cybersource/commerce_cybersource.module, fundraiser/modules/fundraiser_commerce/includes/fundraiser_commerce.credit_card.inc, fundraiser/modules/fundraiser_commerce_cardonfile/fundraiser_commerce_cardonfile.module, fundraiser/modules/fundraiser_ocd/js/fundraiser_ocd.fundraiser.js, fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module, springboard_advocacy/springboard_advocacy.module
Merging 7.x-4.16.1 into 7.x-4.x
=> 7.x 4.16.1 merge

email_wrappers/email_wrappers.module, springboard_advocacy/springboard_advocacy.module
Ensure webform_submission_render() doesn't throw an undefined function error.
=> Include webform.submissions.inc before using _webform_filter_values()
