JacksonRiver/springboard_modules

- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.views_default.inc
This change will require a features revert on Springboard P2P Personal Campaigns.
Alternatively, add the filter manually. On the donor dashboard View, add a filter on P2P Action: Status and set Visible to Yes.
> Adds a filter on P2P action to only show donors with successful donations

- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.module
P2P adds some tokens to email wrappers messages. The problem was upsell sends an email but doesn't include $message['params']['submission'] so a few PHP notices resulted.
This change checks first.
> PHP notices caused by P2P email wrappers token set

- salesforce/salesforce_npsp/salesforce_npsp.module
Added a !empty() check to salesforce_npsp_salesforce_sync_fail_item() to prevent PHP errors when an SF queue item fails to sync and has no sobject value.
> Bugfix: PHP errors from salesforce_npsp_salesforce_sync_fail_item() when sobject is empty.

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
- fundraiser/modules/fundraiser_commerce/tests/fundraiser_commerce.unit.test
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
When fundraiser_sustainers is looking for the sustainer key file, it asks other modules that implement this hook to return a path to the directory where the file lives. The only module to implement this hook is fundraiser_commerce, which is not an explicit dependency.
So during simpletests, fundraiser_sustainers can be enabled without any module implementing this hook and we get an undefined offset and no sustainer key path. As a result the sustainers tests have to enable both modules and we get the extra overhead of fundraiser_commerce.
Since it looks like we didn't make additional use of this hook, my proposed solution is to remove it and let fundraiser_sustainers find its own sustainer key path. It's just doing a variable_get() from the encrypt key path anyway.
> Remove hook_fundraiser_get_credit_encryption_path

- salesforce/salesforce_p2p/salesforce_p2p.module
- springboard_p2p/springboard_p2p.install
- springboard_p2p/springboard_p2p.module
- springboard_p2p/springboard_p2p.views.inc
This moves around the saving of the personal campaign action to accommodate some gateways not invoking the donation post submit hook with enough context.
- The personal campaign action is now saved in the submit callback regardless of its type, which makes the donation post create save no longer needed.
- The donation success hook is used instead of donation post submit. It looks up the previously saved record and adds the donation amount to that and to the personal campaign progress.
- Removed unused fields from a db query in salesforce_p2p.
- Added a status column to the personal campaign actions table so that actions won't be visible until the donation is successful. For webform_user actions, the action is immediately visible.
> P2P donations not counting towards personal campaign progress when using Paypal IPN

- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/commerce_litle.admin.inc
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/commerce_litle.info
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/commerce_litle.install
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/commerce_litle.make.example
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/commerce_litle.module
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/includes/LitleSDK.php
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/tests/commerce_litle_test.module
This goes along with the matching branch of the Springboard build repo.
- Switched to using the libraries module for a definition of the Litle SDK. It now uses that for autoloading the needed files.
- Added an example make file, like how salesforce_soap does.
- Added a LitleSDK class to abstract the interactions between the Litle SDK and Commerce Litle.
- Adjusted XmlParser and LitleOnlilneRequest calls in commerce_litle to use the LitleSDK class.
> Litle SDK version 8.27.1

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- Replaces strtotime('now') in a few places where being off by a second or two shouldn't matter.
- Changes the by_member() call on the sustainer edit form to by_masterdid().
- Updates the by_member() query to use the base table in the WHERE clause instead of the joined table.
- Creates a count remaining donation query that doesn't use a LEFT JOIN or ORDER BY and does the count inside the query. This is used on the sustainer edit form and on the donation success hook implementation.
> Sustainers performance enhancements

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
This adds the fundraiser_status property to each Commerce order status. It sets the value to FALSE for non-fundraiser statuses.
If the popertry is only added to the fundraiser statuses then Undefined index errors will appear on the donation stage mapping form.
> Add fundraiser_status value to each order status

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
This value needs to be here so the 'skipped' status can be mapped to an SF stage.
> Add 'skipped' to list of used order statuses.

- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.features.field_base.inc
- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.features.field_instance.inc
- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.info
- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.install
(originally PR https://github.com/JacksonRiver/springboard_modules/pull/683)
Changed p2p ms referrer and p2p ms initial referrer to textareas in an update hook and updated the features.
This reverts the p2p personal campaign feature for fields when the update hook is run.
> Change some market source p2p personal campaign fields to textareas

- form_layouts/form_layouts.module
This update reinstates the template specific css class that form layouts would add to the form element. This feature was lost during updates to form layouts in 4.5.
> Reinstating template specific css class on form element.

- page_wrappers/page_wrappers.module
This update will preserve the order of the css files as they are defined by the theme.
> Maintain the order of css files when including them from a theme

- springboard/modules/springboard_admin/springboard_admin.module
This was wiped out when we merged in the support for sub-paths for SB Admin.
Original commit sha: ecf708b1397e6a5ec8e456c907c33a3ba0008485
> Restoring fix for the way menu titles are changed. 

- fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers_health_checks.test
- secure_prepopulate/dynamic_gift_strings/tests/gift_string.test
Adjusted the sustainers health check test to to match not counting stuck sustainers where the next charge is < 1 hour ago.
Also snuck in a missing comma for a gift strings test.
> Update the sustainers health check test

- fundraiser/modules/fundraiser_commerce/gateways/commerce_payment_example.inc
This updates the example payment fundraiser gateway charge function to work with Commerce 7.x-1.11. In the latest version it expects the credit card pane values to be pass through the $order->data array.
> Resolve PHP notice from example gateway after update to Commerce 7.x-1.11

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_date_mode/fundraiser_date_mode.module
When enabling/disabling the Date mode feature a donation series occuring on the last day of the month would have sporadic charge dates.
The function validating each donation day was not using the next_charge value to determine the day of the charge.
This fix pulls the next_charge value from the database when evaulating the days.
> Date Mode Setting Wrong Date when Transitioning Donations

- salesforce/salesforce_genmap/includes/modules/webform.inc
- salesforce/salesforce_genmap/salesforce_genmap.info
Line 20 of https://github.com/JacksonRiver/springboard_modules/blob/7.x-4.x/salesforce/salesforce_genmap/includes/modules/webform.inc calls a fundraiser hook but fundraiser isn't listed as a dependency of the salesforce_genmap module. This pull request makes it a dependency.
> add fundraiser dependency to salesforce genmap

- springboard/modules/springboard_admin/springboard_admin.menu.inc
Without setting a menu item's module these php notices appear when rebuilding the sb menu:
Notice: Undefined index: module in user_menu_link_alter() (line 1888 of /modules/user/user.module).
Notice: Undefined index: module in user_menu_link_alter() (line 1894 of /modules/user/user.module).
> For sb admin menu items set a default module value.

- fundraiser/fundraiser.module
The Drupal JS Settings array for donation form validation configuration is not added using the $form['#attached'] array, and is therefore not included on the page when a validation error refreshes the page.
> Fundraiser Validation Settings Lost on Form Validation Error

- springboard/modules/springboard_views/springboard_views.install
Added an uninstall hook for springboard_views to remove the Springboard Feed, and added a check when adding the Springboard Feed to edit it if it exists.
I tested this change by disabling, uninstalling, reenabling springboard_views, and running cron via drush (at least 3 rounds of this) and checking the aggregator tables in between steps.  Uninstalling springboard_views will remove the feed and the feed's items.
> Remove Springboard Feed during springboard_views uninstall, and edit it during install if it exists.

- springboard_api/resources/springboard_api.form_resources.inc
- springboard_api/tests/springboard_api.test
Issue:
The API forced the text 'Donate' when submitting donation forms. If the submit button isn't configured to use that word the submission fails to save.
Fix:
Follow the same practice found in other code, and webform itself, that uses the value set in the $node->webform['submit_text'] setting to determine the submit button's value.
Also made some minor changes to the tests to get that working.
> Use configured submit button text when submitting through the API.

- email_wrappers/email_wrappers.module
- email_wrappers/tests/email_wrappers.test
- webform_confirmations/webform_confirmations.module
This cleans up some of the email wrappers and webform confirmation handling.
Investigating the original issue of token replacement not working in standard webform emails (SB ticket 40)  it was discovered the process around token replacement and control over the email sending on donation success was closely tied together.
The changes here make it clear that token replacement and email send control is not supported on standard webform emails.
> Token replacement in webform emails

- springboard_p2p/springboard_p2p.module
Added an extra check to the p2p donation success hook implementation to prevent it from running more than once on the same donation.
> P2P progress discrepancy

- fundraiser/fundraiser.module
Hide the currency field when only one currency is active. When it is displayed move it to the Fundraiser settings group.
> Hide Currency Field When Only One Currency Enabled

- springboard/modules/springboard_admin/springboard_admin.module
- springboard/modules/springboard_views/springboard_views.views_default.inc
The SB admin view was based on the Commerce Customer Profile table. This was causing duplicate entries for each user with more than one customer profile.
This changes the view to be based on the user table.
> Administrator View Showing Duplicate Users

- fundraiser/modules/fundraiser_sustainers/js/sustainer.js
Its currently possible to submit the sustainer cancel form without having changed the default text in the reason field.
This change forces that text to clear if it hasn't been edited.
> Cancel Without Entering Reason

- fundraiser/modules/fundraiser_upsell/fundraiser_upsell.module
This switches hard-coded dollar sign's in the Upsell modal for the node's currency setting.
> Use Node Currency Symbol in Upsell Modal

- springboard_social/scripts/sb_social.addthis.js
If Drupal is installed in a subdirectory, the current ajax call to the 'sb_social' menu callback will produce a 404. This change prepends Drupal.settings.basePath to the ajax call to determine the correct subpath.
> Update sb_social.addthis.js  ajax call to use Drupal.settings.basePath 

- page_wrappers/page_wrappers.module
Issue:
The renaming of page wrapper js and css files to include a timestamp and remove the .txt extension was targeting only the first uploaded file.
Fix:
Adjust the code to allow for files in other deltas to also be renamed.
> Pagewrapper txt Extension Removal Targets First FIle Only

- fundraiser/fundraiser.api.inc
- fundraiser/fundraiser.module
- fundraiser/modules/fundraiser_webform/fundraiser_webform.module
- secure_prepopulate/springboard_cookie/springboard_cookie.module
The original problem is this was a hook that was returning $form_state. So if nothing implemented the hook $form_state would get wiped out. If more than one implementation returned $form_state it would cause a recursion error because it was trying to merge $form_state into itself. So everything works fine if there's exactly one implementation that returns $form_state.
I need this change specifically because I want to change $form_state['redirect'] in a new implementation of this hook.
This changes the hook into a drupal_alter, and updates the api doc for fundraiser, and updates existing Springboard core implementations of this hook to use the alter instead. The known core implementations are fundraiser_webform and springboard_cookie. Only fundraiser_webform returned a form_state. There is …
> Change the fundraiser donation post submit hook to be an alter instead.

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Without setting the timezone on the initial DateTime object for the series it may use the UTC timezone, which could be a day off of the sites current timezone. See http://php.net/date_default_timezone_get for more info on how php selects a timezone.
This fix explicitly sets the timezone on the DateTime object from the site's timezone setting.
> Set the site timezone on the initial DateTime object for a sustiainer series

- salesforce/salesforce_sync/includes/salesforce_sync.sync.inc
Full datetime formatting was using strtotime() to try and convert a unix timestamp to a date. This update checks to see if the value being exported is a timestamp and handles it accordingly.
> Handle unix timestamps in full salesforce date/time fields.

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
Issue:
If a custom module re-arranges the fundraiser fields in hook_fundraiser_field_info_alter it may cause the state field to not interact correctly with the country field selection. For example, it won't switch to a textfield for countries with no pre-set zones.
Fix:
Use the value from form_state first when determining a default value from the country field.
> Use Country Value in form_state When Rendering State (aka Zone) Field

- springboard_advocacy/includes/springboard_advocacy.admin.inc
- springboard_advocacy/modules/sba_message/sba_message.module
- springboard_advocacy/modules/sba_message_action/sba_message_action.install
- springboard_advocacy/springboard_advocacy.install
Both the advocacy and message_action install files improperly referenced the taxonomy field names, omitting the "field_" prefix when checking field existence with field_info_field and field_info_instance. This caused a problem when message action module was disabled/re-enabled.
Also, the creation of the message action field instances was moved to the message action install file.
Hitching a ride in this patch is a syntax fix in two spots in which the number of existing messages was counted in order to determine whether the user-editable option should be disabled on the message add/edit page, and whether a message should be shown on the message landing page  if a message is user-editable. The bad syntax did not result a bug - everything worked as expected - but it was obviously wrong.
> 386 re enabling message action loses taxonomy

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
The Paypal WPS payment gateway does not pass any payment fields data. This code in commerce was expecting it with each donation.
This sets the $scrubbed_fields variable to an empty array if the payment_fields array does not exist.
> Missing Index Error On Paypal WPS Only Forms

- webform_confirmations/webform_confirmations.module
Issue:
In one instance a change to the amount value was not being displayed by the [donation:amount] token.
Fix:
Reload the donation object before rendering and sending the email.
> Reload the Donation Object Before Rendering the Confirmation Email

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
- fundraiser/modules/fundraiser_tickets/components/tickets.inc
commerce_currency_amount_to_decimal() does not pad the decimal places, but commerce_currency_format() does. (ie. 10.5 vs $10.50).
Going forward we should probably encourage the use of the amount_formatted token instead since that'll include the currency symbol and correct formatting.
> Add number_format around currency amount to keep two decimal places.

- springboard_tag/plugins/export_ui/springboard_tag_export_ui.class.php
- springboard_tag/springboard_tag.module
This changes the SB roles setting so a user with the selected role(s) would not see the tag.
> Change the SB Tags role settings to be exclusive vs. inclusive

- springboard_social/includes/sb_social.db.inc
- springboard_social/sb_social.info
This removes the salesforce modules listed as dependencies in sb_social.info, and wraps the one place where a dependency exists with a module_exists().
> Remove Salesforce Modules Requirement From SB Social

- salesforce/salesforce_donation/salesforce_donation.module
Issue:
When a sustainer fails it is missing the transaction date value.
Fix:
This change reloads the donation object before it is queued to SF for syncing. This ensures the latest changes to the object will be used when the values are mapped.
> Reload Donation Object when Queuing a Failed Sustainer

- springboard_tag/springboard_tag.module
Adds an option to add springboard tags to the page head element.
> 7.x 4.8 beta 518 add springboard tag to head

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_sustainers/includes/FundraiserSustainersLog.php
This sets the locked status when donations are locked for processing and passes the current status through to logLockedDonation().
> Missing State Changes in Sustainer Activity Log

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Issue: 
If not card on file record exist a notice is displayed on the sustainer management page.
Fix:
Verify the card on file record has loaded before reading the card number value.
> Warning on Sustainer Management Page

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Issue:
The transaction date time field was being synced for a skipped sustainer, but is empty.
Fix:
This code removes the field from the array of fields.
> Remove the Transaction Date Time Field When Syncing a Skipped Sustainer

- fundraiser/fundraiser.module
- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
This code fixes the handling of the donation and refund amounts on the refund form to support multi-currency and + thousand amounts.
> Correct Usage of Thousand Separator and Multi-Currency in Refund Form

- salesforce/salesforce_message_action/salesforce_message_action.install
This commit maps 2 new message action fields:
* Generated_Message_Count__c
* Message_Edited__c
And adds an update hook to update any existing maps.
> Mapping 2 new message action fields for 4.8

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.info
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers_delayed_creation.test
This adds a queue worker for creating the sustainer series on cron.
Also, there's an add admin setting for control over the cron options so an admin could choose to continue creating the series on donation submit.
> Create Sustainer Series on Cron

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.info
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_sustainers/includes/FundraiserSustainersLog.php
- fundraiser/modules/fundraiser_sustainers/includes/fundraiser_sustainers.views_default.inc
- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_date_mode/fundraiser_date_mode.module
- fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers.setup.test
- fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers.test
- fundraiser/modules/fundraiser_sustainers/tests/fundraiser_sustainers_processing_exception_handling.test
- fundraiser/tests/fundraiser.setup.test
@dbarbar I made some changes to the test to get the sustainers processing.
Initially the sustainers needed a sustainer key.
But, then I found it impossible to process both the success and failure cron runs in the same test, so I broke out the success and failure tests into separate classes and now they both complete.
> Sustainer Processing Improvements

- fundraiser/fundraiser.module
Fix:
Returns false for fundraiser_get_total_donations_by_nids return when result is empty.
> PHP Notice in Goals When no Donations Exist

- springboard/modules/springboard_admin/springboard_admin.module
Thanks to our admin menu path rewriting, the Upsell Preview tab on donation forms is currently redirected to /springboard/node/%/sustainer_upsell_preview, which causes the form's page wrapper to not be applied, thus making the Preview completely unhelpful for styling or preview of what the actually modal will look like.
This patch creates a new entry in the admin menu aliases that makes the paths relevant to the upsell preview exempt from path rewrites.
Assembla ticket no. 596
This replaces Pull Request #797.
> Adding admin menu alias for upsell preview to avoid use of admin UI

- springboard_advocacy/includes/views/springboard_advocacy.views.inc
Hotfix for users seeing "The form has become outdated" error message when creating target groups.
> Fix improper assignent of form token variable

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.reports.inc
Fixes an issue with caching the deliverability report and increases cache time to 1 hour.
> 7.x 4.x hotfix message action report cache

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.components.inc
- springboard_advocacy/modules/sba_message_action/sba_message_action.module
Unlock the mandatory checkbox on component edit screens, and amke the spb_phone non-mandatory by default
> make sbp_phone field non-mandatory by default

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
- webform_ab/plugins/win_conditions/total_conversions.inc
Implement hook_webform_ab_validate_conversion() in message action module to track conversions. Also fixes an undefined array index when a form has no conversions yet.
> Track message action conversions in webform a/b

- webform_user/includes/webform_user.drush.inc
Changes:
Filter empty strings from webform submissions.
Fetch submissions chronologically.
Try/catch on user creation logging to account for multiple submissions by the same user to a single form.
> Webform user drush user creation script updates

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.install
This resolved problems migrating existing sustainer series via the update hook fundraiser_sustainers_update_7013()
Doesn't look like there's a problem with update hooks running out of order as there's already a hook_update_dependencies() in salesforce_npsp.install where I would have added one.
> Added schema cache clear after creating fundraiser_sustainers_series table in update hook.

- salesforce/salesforce_queue/salesforce_queue.module
For Assembla ticket 626
Added an entity label callback for the salesforce_queue_item entity to resolve the issue with VBO having no label to display when confirming entities to be operated upon. Currently, the label I am using is "Salesforce Queue Item #[queue ID]" - this could probably be better/include more information. I will update the pull request if/when I get further instructions on how to change the label.
> re #626 - adding entity label callback for salesforce_queue_item entity

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.install
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_upsell/modules/fundraiser_upsell_salesforce/fundraiser_upsell_salesforce.module
- salesforce/salesforce_npsp/salesforce_npsp.install
- salesforce/salesforce_npsp/salesforce_npsp.module
Shouldn't really be needed if `drush cc all` is being run; just added as an extra precaution.
> Added forced cache refresh for fundraiser_sustainers_series schema to migration update hook.

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- salesforce/salesforce_donation/salesforce_donation.module
Also includes a workaround to prevent canceled donations from following the same logic path as processed sustainer payments.
> Ensure cancellation reason syncs to Salesforce

- salesforce/salesforce_donation/salesforce_donation.module
When mapping donation states to Salesforce opportunity stages (/admin/config/salesforce/salesforce-donation), the select fields currently allow multiple stages to be selected, but should only allow one.
When the state mapping form is [submitted here](https://github.com/JacksonRiver/springboard_modules/blob/7.x-4.x/salesforce/salesforce_donation/salesforce_donation.module#L135), the mapping data is stored in the variable `salesforce_donation_mapped_stages` in this format:
```
a:7:{s:11:"Prospecting";a:0:{}s:7:"Pledged";a:1:{s:22:"pending_future_payment";s:22:"pending_future_payment";}s:6:"Posted";a:1:{s:16:"payment_received";s:16:"payment_received";}s:9:"Withdrawn";a:1:{s:8:"canceled";s:8:"canceled";}s:11:"Closed Lost";a:1:{s:6:"failed";s:6:"failed";}s:4:"Void";a:0:{}s:13:"Auto …
```
> Disabled multiple state selection when mapping Salesforce stages to donation states.

- salesforce/salesforce_social_action/salesforce_social_action.info
- salesforce/salesforce_social_action/salesforce_social_action.install
- salesforce/salesforce_social_action/salesforce_social_action.module
The install file does the following:
* Creates an entity fieldmap for the sba_social_action node type that maps to the action object
* Creates a default fieldmap for sba_social_action submissons that maps to the actions taken object
* Maps the new twitter profile fields added in the social advocacy module to the contact object
> Adding salesforce integration support for social actions

- fundraiser/modules/fundraiser_recent_donors/css/fundraiser_recent_donors.css
- fundraiser/modules/fundraiser_recent_donors/fundraiser_recent_donors.module
- fundraiser/modules/fundraiser_recent_donors/includes/fundraiser_recent_donors.views_default.inc
- fundraiser/modules/fundraiser_recent_donors/js/fundraiser_recent_donors.js
* 800 - Updated min-donation amount field validation error message for clarity
* 801 - refunded donation should not be included in the list
* 801 - partially-refunded donation amount should be reflected in recent donors block
* 801 - Update min opt-in display amount filtering to respect the partial refund amount 
* 802 - Recent donors opt-in placement (changed to bottom of payment info)
* 804 - Prefix/suffix min-donation amount with donation node’s current currency
* 807 - On donation form node clone, also duplicate opt-in settings
> QA fixes to recent donors list

- springboard_advocacy/modules/sba_social_action/includes/sba_social_action.preview.inc
Due to the preview page ajax reload after Twitter authentication, static variables are used to prevent the re-randomization of the randomly selected tweets on social actions which have multiple tweets. This patch fixes an issue on social actions with multiple messages, so that the static variable referencing the index of the array of random tweets is reset after moving to the next message.
> reset static variable when switching among multiple twitter messages

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
- springboard_advocacy/modules/sba_social_action/sba_social_action.module
The previous version sometimes allowed substitution of random nids in the url to produce a page with a php notice rather than access denied.
> tweak preview page access hooks

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
A fix to a display issue we made a few weeks ago impacted the behavior of a session variable we were using to control the visibility of the the quicksign form and error messages, causing inconsistency. This patch removes the session variable and its dependent code, and moves the visibility handling code into the form afterbuild function.
> fix error message/form display consistency issue

- springboard_advocacy/modules/sba_message_action/sba_message_action.install
Update the field_sba_action_flow widget weight on sites already implementing message actions so that it is in the correct top position within the multiflow fieldset on node add/edit pages.
> update the action flow field widget weight on node edit forms

- salesforce/salesforce_p2p/salesforce_p2p.module
The p2p personal campaign id field gets added to all forms and will only be populated if someone submits a form by way of personal campaign. This change ensures that the P2P_Personal_Campaign__c only gets populated with a p2p_pcid is available.
> Only add the P2P personal campaign if it's id is available

- salesforce/salesforce_genmap/salesforce_genmap.install
This wasn't a bug with the query range, the initial query wasn't selecting the right records from salesforce_genmap_map so the $sandbox['max'] variable wasn't being set to the total amount of records.
> Fixed salesforce_genmap device info update not updating all maps

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
The quicksign component was being added (but not activated or visible) by default to every new quicksign-eligible node, even if quicksign was disabled for that node.
> use empty not isset in quicksign_node_insert

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Quicksign was setting the default value of non-webform-user components to NULL instead of the default
> stop quicksign from nulling values of non-profile components

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form_layouts.inc
- springboard_advocacy/modules/sba_quicksign/components/quicksign.inc
- springboard_advocacy/modules/sba_quicksign/css/sba-quicksign.css
- springboard_advocacy/modules/sba_quicksign/sba_quicksign.install
- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
This refactors the quicksign form as a webform component, rather than a separate form.
The same behavior as the original module is expected - except in the case of a quicksign failure: the partial profile information, if it exists, is not populated into the webform, to protect user privacy.
> 7.x 4.x quicksign webform integration component

- market_source/market_source.module
Using the MobileDetect to check for an empty user agent instead of something like empty($_SERVER['http_user_agent']) because MobileDetect checks for all possible locations of the user agent string.
> Added check for empty user agent before populating device info fields.

- springboard_tag/springboard_tag.info
Fixes the configure link for Springboard Tags at /admin/modules
> Updates Springboard Tag config link

- springboard_api/resources/springboard_api.form_resources.inc
Webform needs the $webform_submission variable to be cast as an object and not an array. Currently no custom fields are being saved by the Springboard API.
> Re #839 - use object instead of array in submit

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
Addresses: https://www.assembla.com/spaces/springboard/tickets/832-cloning-message-action-loses-custom-confirmation-failure/details
> Clones custom fail message on message actions

- springboard_advocacy/modules/sba_message/js/sba_message.js
On the message admin page, if you choose a state and then a district from the select options, various fields become disabled. Clicking the reset link clears and undisables them. The text entry "first name or last name" field was not becoming re-enabled after reset.
> Reset text search field

- salesforce/salesforce_message_action/salesforce_message_action.install
- salesforce/salesforce_petition/salesforce_petition.install
- salesforce/salesforce_social_action/salesforce_social_action.install
- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
1. Make quicksign form stay visible, even after validation failure.
2. Adds a field to sync with salesforce quicksign flag.
3. Makes validation failure less messy:
On single-step, editing-required quick-signed message actions, if the user passes validation, but the required editing fields don't because they have not been changed, only the required editing fields will be made to error - no more long list of "x field is required" for the user fields, when the quicksign button is clicked. If the required-editing fields are changed by the user, and then quicksign is clicked again, the form will submit successfully.
Also, the message action required-editing fields will get outlined in red if they fail validation because the user did not change them. Previous there no indication in the UI, …
> 7.x 4.x 840 quicksign keep visible

- springboard_advocacy/modules/sba_message/sba_message.admin.inc
- springboard_advocacy/modules/sba_message/sba_message.module
- springboard_advocacy/springboard_advocacy.module
Clone message entities when cloning actions.
In hook_insert, the cloned node still has the original node's message entities loaded but not saved. Recast them as new, unset some API values, replace the entity reference ID with our new node ID, and save them as new messages.
Then create a new record in draggable views table with the original nodes weights.
Then save the target and message info to the API server.
> 7.x 4.x 526 clone message entities

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.preview.inc
- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.webform.inc
- springboard_advocacy/modules/sba_social_action/includes/sba_social_action.preview.inc
- springboard_advocacy/modules/springboard_petition/springboard_petition.module
- springboard_advocacy/springboard_advocacy.module
Create a success hook for actions.
This required changing the order in which submit hooks are executed for message actions, from the message action hook firing first, to firing after webform and webform user, so that the user account info is available when single-step message actions are submitted.
> 7.x 4.x 889 advocacy success hook

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
- springboard_advocacy/modules/sba_social_action/sba_social_action.module
- webform_ui/webform_ui.admin.inc
- webform_ui/webform_ui.module
This makes it possible to edit hidden fields on the results page of all webform types.
It also fixes a bug that resends actions to the transaction server if the submission is edited.
> make hidden fields editable on submission results for all form types

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
- springboard_advocacy/modules/sba_social_action/sba_social_action.module
inclusion of form layout markup on submission result pages was causing some CSS in springboard backend to mark the layout containers as display:none.
> remove form layouts from results pages on actions

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Some unset values were causing php notices when newly enabled action modules' example nodes were being created and quicksign was enabled.
> remove some php notices

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
I missed one location in the earlier pull request that removed form layouts from results pages.
> suppress form layouts on message action results page

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Quicksign settings were being reverted to default when node_save was being called from locations other than the node edit form.
Modified to load the quicksign settings in hook_node_load, which allows the quicksign save function to be simpler, and also fixes a previously undiscovered issue with node cloning not cloning quicksign settings.
> 7.x 4.9.2 beta2 914 quicksign reverted labels

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Leave the quicksign flag in place once it exists, even if quicksign is disabled, so that old submissions don't lose data.
> don't delete the quicksign flag

- market_source/market_source.module
Mobile detection script was updating device details on webform result edit pages, replacing the original user's device details with the administrator's.
This patch simply moves the device detection code up into a previously existing control structure which tests whether the $form['#submission'] object exists (and thus we are on a results page).
> don't load MS device detection on submission result pages

- fundraiser/modules/fundraiser_tickets/fundraiser_tickets.module
Add on donations use the $donation->donation array as a proxy for webform submission data, and the payment_fields['credit'] data is not nested as webform expects.
> fix credit expiration formatting on addon donations

- page_wrappers/page_wrappers.module
- springboard/modules/springboard_admin/springboard_admin.module
I've created a new configuration in the Springboard Admin module that allows an administrator to specify which themes are listed for users that get the Springboard Admin UX in a Page Wrapper node's "include theme CSS" option.
The new administrative option:
And the changes as seen on a new Page Wrapper form:
> 7.x-4.x #222 restrict pagewrappers theme css

- springboard_advocacy/includes/springboard_advocacy.admin.inc
- springboard_advocacy/includes/springboard_advocacy.smarty_streets.inc
- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_social_action/includes/sba_social_action.form.inc
- Don't do a smarty API lookup if there is a form validation error.
- Optionally log smarty calls to watchdog.
> log smarty calls, and prevent smarty calls if form error is not empty

- springboard_honeypot/springboard_honeypot.admin.inc
- springboard_honeypot/springboard_honeypot.info
- springboard_honeypot/springboard_honeypot.install
- springboard_honeypot/springboard_honeypot.module
We don't want to use the built-in Honeypot trigger to immediately block all Honeypot rejections. However, we do want to block IPs that have multiple Honeypot rejections.
This module will block IPs after a configurable number of failures. The default is 50, which is high enough to target spammers using scripts/bots, but safe for other traffic.
Keeping the name of this module generic enough so we can expand on Honeypot integration down the road.
> Add springboard_honeypot module to block IPs after N Honeypot rejections

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.webform.inc
Changes implemeted for the message action success hook broke token replacement in single step message actions which have redirects set.
This patch restores the previous execution order the message action submit hook (prior to webform's submitters), creates a new submit which fires after webform has processed the form, and moves the single step success call from the message_action.webform.inc file into the new submit hook. Unfortunately, this means putting more response data into session.
> move single step message action success hook into submit function

- springboard_honeypot/springboard_honeypot.admin.inc
- springboard_honeypot/springboard_honeypot.module
Create a setting that allows admins to exclude the honeypot timer from specific forms.
> Adding a honeypot timer blacklist setting.

- fundraiser/modules/fundraiser_upsell/modules/fundraiser_upsell_salesforce/fundraiser_upsell_salesforce.module
If no upsell overrides are configured in marketsource settings, upsell donations will trigger a php notice about missing per node settings.
> fix php notices if no MS upsell overrides are configured

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
If a payment method settings has never been re-saved, $settings['payment_method'] is a single-character string rather than an array, causing a php notice. It essentially means you have an active payment method which has not been configured, or perhaps not reconfigured after an update which has added more config options, as the dual ask amount seems to have introduced.
> make sure payment method settings is an array

- springboard_hmac/springboard_hmac.module
The module should now be able to correctly validate Salesforce generated tokens.
> Changing the payload delimiter to a period per spec.

- springboard_honeypot/springboard_honeypot.module
For each $blacklist element, also run `trim()` in case newlines are `\r\n` and not just `\n`.
Also, simplifying the unset logic.
> For each $blacklist element, also run `trim()` in case newlines are `\r\n` and not just `\n`

- springboard_honeypot/springboard_honeypot.module
For each $blacklist element, run `trim()` to trim any whitespace from the end of the form IDs entered in the admin field so we can do a string compare with `$form['#form_id']`. Borrowed this use of `array_map()` from Drupal core.
Also, simplifying the unset logic.
> Run `trim()` for each $blacklist element in Springboard Honeypot timer blacklist

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
The value of $next_donation->data['cardonfile']  can be "FALSE" when the example payment method is used, which causes an array_flip() error in entity_load().
> use empty rather than isset in cardonfile check

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module
- springboard_hmac/springboard_hmac.module
add two error statuses to stop in tracks criteria
don't save failed hmac validations to prevent spam flooding
> tweak failure handling in hmac and sustainers upgrade

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
This update re-saves the sustainers_series entity with the new donation amount. The save operation will cause the object to resync to Salesforce if the entity mapping module is enabled and configured to send updates.
> Saving the sustainers_series object after donation amount is updated.

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- salesforce/salesforce_donation/salesforce_donation.module
In addition to the new hook, the queueing of the future donations has been moved into the salesforce_donation module via implementation of the new hook.
I tested both real-time and delayed sustainer creation and orders are being queued as expected.
> Adding new hook for sustainer order insertion.

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module
- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/includes/install/fundraiser_sustainers_upgrade.install_example.inc
This changes some default text and allows the upgrade tokens to be used on the confirmation page, after some changes from last week broke them there.
> Change sustainer upgrade default text and tokens.

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
I removed the block of code following this:
// Make sure our form_alter hooks in payment gateway include files are always loaded.
> Removed unneeded gateway-specific include code 

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module
This updates anonymous sustainer upgrade webform submissions with the user ID in the payload, then resets the webform_get_submission static cache.
Also a few code style fixes.
> 7.x 4.10 beta1 1021 sustainup webform submission

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module
- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/includes/install/fundraiser_sustainers_upgrade.install_example.inc
- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/includes/install/fundraiser_sustainers_upgrade.install_fields.inc
Merge conflict resolution accidentally regressed some default text.
Also, this fixes some php notices that were occurring during acceptance tests due to the redirect url having no default value.
> undo a regression in sustainer upgrade default text

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
- fundraiser/modules/fundraiser_commerce/gateways/commerce_authnet.inc
- fundraiser/modules/fundraiser_commerce/gateways/commerce_paypal_wps.inc
hook_form_rules_ui_edit_element_alter() will not work consistently when implemented in the fundraiser gateway include files. This patch renames the implementations in authnet.inc and paypal_wps.inc and calls them dynamically from fundraiser_commerce_form_rules_ui_edit_element_alter() instead, which is properly situation in a .module file.
It also fixes a fatal error that occurs when trying to access the payment method rule reaction settings from Rules UI menu paths instead of commerce payments UI menu paths.
The diff looks larger than it really is because of line indentation changes from the removal of two unecessary control structures wrapping the rest of the code in the hooks.
The following control structures were removed from the top of the hook implementations:
// This test is …
> 7.x 4.10 beta1 1017 paypal and authnet settings lost after save

- salesforce/salesforce_sync/includes/salesforce_sync.sync.inc
A new issue arose during the course of the pwmb work: when trying to sync an 'authorized' but not yet charged donation, the following soap error is thrown on the batch:
''' is not a valid value for the type xsd:dateTime'
Salesforce_sync.sync.inc unsets empty date fields but not datetime fields. This PR alters salesforce_sync.sync.inc to unset datetime fields in the same way as date fields.
> re #739 - unset empty datetime values

- webform_user/includes/webform_user.drush.inc
Batches would only process one record at a time because Drupal core would take the "71,1234,43" string as integer (71).
Use `$chunk` as array and let `db_query()` do the db placeholders.
> Batches only process one record at a time; use $chunk as an array

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_social_action/includes/sba_social_action.form.inc
A few webform fields in message and social actions were subject to breakage if moved into new fieldsets by a client. This prevents their values from being lost.
> 7.x 4.x 881 add parse components logic to actions

- springboard_p2p/includes/springboard_p2p.password.inc
One time password reset URLs sent from /p2p/password can be invalidated before the recipient has a chance to visit the link by certain email clients (outlook.com, etc). 
Since the current behavior for these one-time links is to immediately log in the user, if the links are visited by bots or fetched through preview functionality, they are effectively used before a user has an opportunity to change their password.
Changes:
- Prompt user to click a button to continue to log in on /p2p/set_password/[uid]/[timestamp]/[hash] pages. (This is the default behavior on /user/reset/ in Drupal core.)
- Adds required $uid paramter to  user_pass_rehash() call to suppress php notice.
- Adds SESSION token from user.pages.inc
> 7.x 4.x P2P prompt for log-in on password reset links

- webform_user/includes/webform_user.drush.inc
See https://www.assembla.com/spaces/springboard/tickets/1092-webform_user_create_missing_users-drush-command-can-create-users-with-blank--quot-name-quot--value--throw-p---/details
> Do not create user accounts for submissions with empty $submission['mail']

- fundraiser/fundraiser.module
Don't display "There are no Fundraiser settings to display" when there actually are settings to display on the node creation form.
> Fix "There are no Fundraiser settings to display" message

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_message_action/sba_message_action.module
This patch limits the subject field length to 70 characters on the message action message edit form, and on the webform client form if the subject is editable.
> limit message action subject line to 70 chars

- springboard_advocacy/modules/springboard_petition/springboard_petition.install
This patch adds and re-weights the webform user internal name field on petition nodes, on install and in an update hook (if it does not exist already);
> restore internal name field on petitions

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.form.inc
- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.modal.inc
if js was disabled, clicking "view all possible mesages" link caused a fatal.
This patch overrides ctools link function to add target = _blank to the href so if there is no modal the mesage preview gets served in a new window, instead of displaying the php error.
> open message preview in new window if js is disabled

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
- fundraiser/modules/fundraiser_tickets/components/tickets.inc
- springboard_measurement_protocol/README.txt
- springboard_measurement_protocol/includes/springboard_measurement_protocol.admin.inc
- springboard_measurement_protocol/springboard_measurement_protocol.info
- springboard_measurement_protocol/springboard_measurement_protocol.install
- springboard_measurement_protocol/springboard_measurement_protocol.module
This PR adds a module, "springboard_measurement_protocol", which allows tracking PayPal events in GA by utilizing Google's Measurement Protocol service.
@pcave I had more work done, and I might commit it to another branch, but it involves abstracting some of the Measurement Protocol functionality into a different module and providing a class to construct and deliver a payload to the service. But I think this would be classified as "scope creep" so stopped and can work on it later if desired.
> 994: Implementing GA tracking for PayPal transaction events.

- webform_user/webform_user.module
Small performance gain by moving array_keys() out of the foreach.
> Reduce 32+ calls to array_keys()

- springboard_p2p/includes/springboard_p2p.register.inc
- springboard_p2p/plugins/content_types/login_intro.inc
- springboard_p2p/springboard_p2p.module
This change allows a handful of default values to be passed-through the registration process. Passed through values will be used to pre-populate the personal campaign node add form.
> Personal campaign default values pass-through

- fundraiser/modules/fundraiser_webform/includes/fundraiser_webform.goals.inc
- webform_goals/webform_goals.admin.inc
- webform_goals/webform_goals.module
- Corrects errors on the goals list page which occur when the node associated with a goal has been deleted.
- Updates node deletion so any associate goal data will also be removed from the database.
> 7.x 4.x 46 correctly handle goal data after node deletion reroll

- springboard/modules/springboard_admin/springboard_admin.menu.inc
Limit the springboard admin link to "Adminstrator" role rather than "administer springboard" permission because "Springboard Admin" should not be able to access this link.
> limit springboard admin settings to the built-in administrator role

- springboard_advocacy/modules/sba_message_action/includes/sba_message_action.reports.inc
extra white space and a bad regex mangled the download url.
presumably  preg_replace("@//@", "/", ...
was meant to remove double / at the end of the url, not in the "https://"
> 7.x 4.11 beta 1061 message download

- springboard_api/resources/springboard_api.form_resources.inc
- springboard_api/springboard_api.module
Add handling for Advocacy message actions (single-step) to springboard API.
Modify springboard api to handle non-webform fields.
Alter output returned from API server if advocacy is enabled to include transaction server response.
> Springboard API extension for Advocacy message actions

- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle.inc
It seems like the comment on line 517, before a call to commerce_litle_fundraiser_commerce_update, is written in error: it references authorize.net. I've updated that comment in this PR.
> Remove errant comment in Litle module

- springboard_dw/includes/springboard_dw.api.inc
- springboard_dw/includes/springboard_dw.queue.inc
- springboard_dw/modules/springboard_dw_queue_legacy/springboard_dw_queue_legacy.drush.inc
- springboard_dw/springboard_dw.drush.inc
- springboard_dw/springboard_dw.module
This hotfix creates a utility wrapper for logging that all data warehouse module logging gets funneled through so there is a centralized check for if watchdog logging is enabled.
> 7.x 4.11.2 hotfix dw

- secure_prepopulate/dynamic_gift_strings/dynamic_gift_strings.module
Ooops. Encoded url params are already decoded when retrieved from $_GET. We need to re-encode them.
> urlencode gift string after retrieving it

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module
This update ensures query params are passed along to the action after HMAC validation.
> Pass query params to sustainer upgrade form if they exist

- fundraiser/modules/fundraiser_upsell/modules/fundraiser_upsell_salesforce/fundraiser_upsell_salesforce.module
This should prevent duplicate upsell objects from syncing to Salesforce.
> Check to see if an upsell object has already been exported.

- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle/commerce_litle.module
In commerce_litle.module on line 466 there is a space between "&" and "session_id." I believe this space is errant: it is causing a 'Failed to load resource: the server responded with a status of 400 (Bad request)' error in the console on a client site.
> re #1130 - remove errant space

- springboard/modules/springboard_admin/springboard_admin.module
- springboard/modules/springboard_views/springboard_views.views_default.inc
Adding ‘create user’ button to Administrators view and corresponding Admin UI alias for user creation page.
https://app.assembla.com/spaces/springboard/tickets/1080-administrator-view--add---39-create-new-user--39--button/details
> re #1080 - adding ‘create user’ button

- fundraiser/modules/fundraiser_designations/fundraiser_designations.module
- fundraiser/modules/fundraiser_designations/js/fundraiser_designations.js
There are additional commits sonce this was last merged. three fixes:
1. Incorrect field name in select query was causing pdo on product delete confirm page.
2. The state of the recurring donation option was not being maintained after a page refresh, and was returning to the default value when dual ask amounts was enabled with radio options and checkbox. This caused the items in the cart to be out of sync with the recurring option. A form repopulator function was added to complement the cart repopulator function - saving the current value in a cookie which persists until submission.
3. when dual ask is enabled and items have been added to the cart, the dual ask element is disabled to prevent it from being out of sync with items in the cart. Setting the element to disabled caused the value …
> 7.x 4.x fundraider designations and portal

- springboard/springboard.admin.inc
- springboard/springboard.install
This patch converts the sbp referrer fields to long text. It's like the patch in P2P that converts the MS referrer fields to long text, except that the P2P patch only changes the field storage, not the field instances, which in the Drupal UI continue to be textfields on the profile page. This patch converts the intances too, so that they display as textareas and do not truncate the referrer data like the p2p/ms fields doif the user is re-saved by an admin. If we don't care about that, then the instance conversions could be removed, although that would mean making the field storage config not in sync with the field instance config.
> convert sbp referrer fields to textarea

- secure_prepopulate/springboard_cookie/springboard_cookie.module
In addition, this change also resets the cookie with profile values whenever a user logs. It also fixes an issue that caused cookie data to get updated with another user's info when using the built-in user edit page.
> Adding a debug page to output cookie info.

- springboard_advocacy/includes/views/handlers/springboard_advocacy_views_handler_field_target_actions.inc
1. Create a target group with parameters "federal representatives | republican"
2. Search for targets with parameters Federal senators | Republican
3. Try to add an indivial senator to the recipients block.
Result: incorrect dupe target notice.
Cause: the 'Add' link is missing the 'role' paramter, so the duplication warning is triggered by the party parameter only.
> fix duplicate detection issue

- fundraiser/modules/fundraiser_sustainers/modules/fundraiser_sustainers_upgrade/fundraiser_sustainers_upgrade.module
Fixes a php notice which occurs on webform confirmatin pages when sustainer upgrade is enabled.  Adds checks for:
1. That we are on a confirmation page belonging to the sustainer upgrade node type;
2. That the session var exists.
> check for session before unsetting it.

- page_wrappers/page_wrappers.module
Currently, fundraiser-redirect pages do not get a page wrapper, leaving them to have the bare-bones springboard_frontend theme styling (pretty much none). This patch applies the donation form's page wrapper to the fundraiser-redirect page and will make it easier to add other donation form sub-pages (via code) in the future.
https://app.assembla.com/spaces/springboard/tickets/683-paypal-cancellation-screen-is-not-themed/details
> re #683 - make donation form’s page wraper apply to fundraiser-redirect

- springboard/modules/springboard_admin/springboard_admin.module
Original "assign user roles" patch was missing a form ID, and did not remove the administrator role from the possible role assignments.
Also adds a config form to Springboard Admin settings to select which user roles should be excluded from the assign user roles permission.
Uses the same approach user.module implements to disable "authenticated user" checkbox to disable disallowed role checkboxes.
related: https://github.com/JacksonRiver/springboard/pull/21
> 7.x 4.12 beta 1139 user role assign

- fundraiser/modules/fundraiser_quick_donate/fundraiser_quick_donate.module
- fundraiser/modules/fundraiser_quick_donate/includes/fundraiser_quick_donate.fundraiser.inc
- salesforce/salesforce_quick_donate/salesforce_quick_donate.module
The quick donate module needed new hooks to announce a card was being opted out. The salesforce module now operates on these hooks to push the opt-outs to Salesforce.
> Add Salesforce integration support for quick donate opt-outs

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_sustainers/includes/fundraiser_sustainers.views_default.inc
The unlock sustainers action and VBO were created 5 weeks prior to the addition of the "locked" status code on July 31. The omission of the locked status from the action and VBO was an oversight. This patch restores the ability to unluck sustainers with a status of "locked" in addition to the prior eliglbe statuses "processing" and NULL.
> add unlocked status to stuck sustainers vbo and action

- springboard_advocacy/modules/sba_message_action/sba_message_action.module
- springboard_advocacy/modules/sba_social_action/sba_social_action.module
- springboard_advocacy/springboard_advocacy.module
The node form submit and validate hooks on message and social actions we're improperly assigned to the submit button, which would cause Drupal to ignore any other custom validate and submit hooks defined elsewhere for those forms. Move the submit logic to a helper function called from hook_node_insert() and hook_node_update()
https://github.com/JacksonRiver/springboard_modules/pull/1154 won't work without this.
> move action node form submit logic to helper function and insert hook

- springboard_hmac/springboard_hmac.admin.inc
- springboard_hmac/springboard_hmac.module
Improves config options for springboard hmac error page:
1. Removes default page title, makes title configurable.
2. Implements filter formatted error message body input.
3. Adds config link to springboard settings
4. implements hook_springboard_admin_alias_patterns().
> improve springboard hmac config settings

- springboard_social/sb_social.module
PREVENTS NON-NUMERIC VALUES from creating a pdo exception on form submissions with invalid social share ids
> remove bad values from social_referer_transaction field

- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
- fundraiser/modules/fundraiser_commerce/gateways/commerce_authnet_echeck.inc
- fundraiser/modules/fundraiser_commerce/gateways/commerce_authnet_echeck/commerce_authnet_echeck.info
- fundraiser/modules/fundraiser_commerce/gateways/commerce_authnet_echeck/commerce_authnet_echeck.module
- fundraiser/modules/fundraiser_commerce/gateways/commerce_authnet_echeck/includes/commerce_authnet_echeck.echeck.inc
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
This code adds a payment gateway for authnet echeck.net. One-time and initial recurring transactions take place using AIM, subsequent payments take place using CIM. This code does not include any support for refunds.
> re #1193 - add support for authnet echeck.net

- fundraiser/fundraiser.install
- fundraiser/fundraiser.module
- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.install
- fundraiser/modules/fundraiser_commerce/fundraiser_commerce.module
This update stores the card_id that was stored after a successful donation in the fundraiser_donation table. This will make it possible to query which stored card is attached to a sustainer series.
TODO
* There currently isn't an upgrade path. Ideally the update hook would load all existing donations, extract the card_id from $donation->data and store it in the new location. This will require a batched operation because it will require loading every donation.
> Store card_id in fundraiser donation

- fundraiser/modules/fundraiser_designations/fundraiser_designations.install
- fundraiser/modules/fundraiser_designations/fundraiser_designations.module
- fundraiser/modules/fundraiser_designations/includes/fundraiser_designations.taxonomy.inc
Make the donation amount field on line items uneditable if the donation product is in a specific category.
> lock recurring doantion amounts on specific designation categories

- fundraiser/modules/fundraiser_designations/components/designations.inc
previously, no radio options were being set as the default value within a designation group's set of radio inputs.
> Adding support for default ask amount options on designation groups.

- fundraiser/modules/fundraiser_designations/js/fundraiser_designations.js
Changing "minumum" to "minimum", affects JS targeting of minimum amount messages in page wrapper JS
> Fixing a typo in the minimum amount message for designations

- fundraiser/fundraiser.module
As noted in #1458, I think this was meant to be a drupal_alter on creation. Module_invoke doesn't take params by reference. I've also removed the $did param, as altering it at this point in the function would have no affect.
> re #1458 - replace module_invoke with drupal_alter

- webform_user/includes/webform_user.drush.inc
`_webform_user_save_profile_map()` now requires `$form` and `$form_state` to be passed by reference as 3rd and 4th parameters.
Regression introduced by https://github.com/JacksonRiver/springboard_modules/commit/fa87b52d1a61186b46360ec175f1460c625a4450 for https://app.assembla.com/spaces/springboard/tickets/936.
@robertromore @pcave - I'm passing empty arrays for `$form` and `$form_state` here. I'm not sure whether any future alter hook implementations will expect either array to have any keys/values in it, so if there's a better way to handle this, I'm fine to drop this PR.
> Fix regression in `webform_user_create_missing_users_batch_process()`

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Per ticket #1466, sustainers currently checks for the update callback on the master donation's gateway, rather than the next donation. If the series's gateway was changed mid-series, sustainers can fail to display the billing update form because the initiating gateway lacked an update callback, even though the updated gateway has one. This PR alters sustainers to check the next_donation's update callback.
> re #1466 - check next donation update callback

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.drush.inc
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Sustainers can now be processed via a drush command! The --uri passed in must match the configured sustainer key or processing will not happen. This pull request also adds the ability to pass a maximum number of sustainers to process.
`drush fsp --limit=50 --uri=https://7x.local `
> Drush command for sustainer processing

- fundraiser/modules/fundraiser_offline/fundraiser_offline.module
Data is already saved as expected in Drupal. This change only affects the data sent to Authoriz.net when creating the CIM Profile.
> Use email from user instead of order if offline

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
Unset the quicksign component values from form state values after validation and prior to submit because it is not needed and the form alterations in it cause a php notice if allowed through.
> fix php notice in quickcsign

- webform_confirmations/webform_confirmations.module
The related record in webform_confirmations_submissions is not cleaned up when a submission is removed.
> Implement submission delete hook to clean up leftover record

- fundraiser/modules/fundraiser_designations/js/fundraiser_designations.js
After the aggregation into the cart of multiple landing pages was enabled, there was problem: reloading the page would cause another item to be added to the cart; also navigating to another and then using the back button would do the same. Placing #fdprocessed into the anchor tag was the solution to that problem. A cookie that used the same ffdprocessed flag wouldn’t work because it is persistent -  yes, it would prevent the accidental addition of items on reload and back navigation, but it would also prevent the aggregation of multiple landing pages.
a different cookie approach might work: one where we place the actual query parameters into the cookie instead of the fdprocessed flag. That way we could compare any loaded parameters to the stored parameters, and only add to the cart if the …
> use cookie instead of location hash to prevent dupe cart items

- salesforce/salesforce_donation/salesforce_donation.install
- salesforce/salesforce_genmap/salesforce_genmap.install
- salesforce/salesforce_message_action/salesforce_message_action.install
- salesforce/salesforce_petition/salesforce_petition.install
- salesforce/salesforce_social_action/salesforce_social_action.install
- secure_prepopulate/secure_prepopulate.components.inc
- secure_prepopulate/secure_prepopulate.install
- secure_prepopulate/secure_prepopulate.module
Adds the autofilled webform component flag to webforms and salesforce mappings.
Some code duplication in salesforce_genmap.install update hooks 7002 & 7003, but I'm reluctant to modify a pre-existing hook. They could use a common helper function however, and perhaps there will be more similar updates in the future.
> 7.x 4.x 927 prepopulate autofill flag

- springboard_advocacy/includes/views/plugins/springboard_advocacy_views_plugin_query.inc
On the advocacy custom groups landing page, if there are two views blocks on a page, you need to update page info on both of them, even if one has no result, otherwise you get a php notice.
> fix pager notice - update page info even if no result

- fundraiser/modules/fundraiser_commerce_cardonfile/includes/fundraiser_commerce_cardonfile.fundraiser.inc
Fixes an issue where a fatal error occurs if a post update hook tries to resave a card that has been deleted.
> do not try to resave a deleted card post update

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Some gateway info arrays don't have an offsite recurring index. This patch prevents php notices when that is the case.
> test for existence of offsite config prior to lookup

- secure_prepopulate/secure_prepopulate.install
I forgot to change the field name when I copied the code block for this update hook. The result was that the autofill field was not being added to actions, instead of the proper result of not adding the autofill field when it already exists.
> fix incorrect field name in secure prepop update hook

- springboard_p2p/springboard_p2p.module
Add support for a flag on personal campaign nodes to suppress the create personal campaign Rule event from firing.
Note that this isn't currently used by Springboard core but is used for a custom registration flow.
> 1726 Suppress P2P create personal campaign Rule event.

- springboard_p2p/modules/springboard_p2p_fields/springboard_p2p_fields.install
- springboard_p2p/modules/springboard_p2p_personal_campaign/springboard_p2p_personal_campaign.install
- springboard_p2p/springboard_p2p.install
- springboard_p2p/springboard_p2p.module
This pull request also fixes a bug where precision was getting lost for non-whole number donations because field_data_field_p2p_campaign_progress.field_p2p_campaign_progress_amount was an integer rather than a floating point value.
> 1608 let p2p campaigns show refunds adjustments

- springboard_dw/modules/springboard_dw_queue_legacy/springboard_dw_queue_legacy.drush.inc
- springboard_dw/modules/springboard_dw_queue_legacy/springboard_dw_queue_legacy.install
- springboard_dw/modules/springboard_dw_queue_legacy/springboard_dw_queue_legacy.module
Some records don't have created timestamps, so sorting queries by that field is problematic. This can cause records to get skipped when queuing them up for the DW. 
Sort by  ID instead.
> 1866 dw skipped records

- springboard/modules/springboard_admin/springboard_admin.module
This adds the ability for other modules to alter the access to the marketing and reports menu items.
I didn't think  we need this need this for the ACLU groups integration, but you never know what others might want.
> make marketing and integration menu access alterable

- springboard_advocacy/modules/sba_quicksign/sba_quicksign.module
- webform_user/webform_user.module
Creates a hook to allow other modules to disable webform_user session storage during a submission.
> prevent session storage after quicksign

- springboard_api/includes/springboard_api.admin.inc
- springboard_api/plugins/api_management_services/basic/springboard_api.basic_service.inc
- springboard_api/springboard_api.module
Unifinished admin UI for sb api was genreating php notices. This patch removes the API key edit link, which is unneeded, and fixes delete link so that it actually works.
> 1699 add delete function to sb api key management

- fundraiser/modules/fundraiser_commerce/gateways/commerce_cybersource.inc
- fundraiser/modules/fundraiser_commerce/gateways/commerce_litle.inc
- fundraiser/modules/fundraiser_commerce/gateways/commerce_payment_example.inc
commerce_payment_validate_credit_card_type() doesn't exist during upsell doantions that are charged immediatel on some gateways. Updates affected gateways to match what the functioning gateways do: include commerce_payment.credit_card.inc prior to calling the validate function.
> 1428 Include commerce file to prevent upsell error

- fundraiser/fundraiser.module
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
Don't use a comma separator when formatting retrieved minimum donation amount configurations on the node edit form.
> Fix min amount formatting for amounts >= 1000

- springboard_advocacy/modules/sba_leg_lookup/includes/sba_leg_lookup.block.inc
This PR changes the President and Vice President values of the US to "Executive Office of the President" and "Office of the Vice President."
> re #686 - alter names for executive branch offices

- salesforce/salesforce_genmap/includes/modules/salesforce_mapping.inc
- salesforce/salesforce_merge_handler/salesforce_merge_handler.info
- salesforce/salesforce_merge_handler/salesforce_merge_handler.module
When Contacts are merged in SF, one of them gets deleted, and we may end up with a Drupal user associated to a Contact that no longer exists. The next time the Drupal user is synced, SF returns a ENTITY_IS_DELETED error. 
This module looks for those errors and, when found, deletes the salesforce_sync_map record associated with it, and refreshes the sync item (as an UPSERT instead of UPDATE). The next time the salesforce sync process runs, the email should match the "other" Contact and we end up with a Drupal User associated with the right Contact.
> 1069 Adds salesforce_merge_handler

- springboard_social/plugins/social_networks/twitter/twitter.inc
This updates the twitter plugin to load the correct plugin js file, instead of loading the email plugin's js. Looks like maybe a copy/paste error. Currently the share text message for twitter shares is incorrect if springboard social is using AddThis as a result.
> Use correct plugin js for twitter for AddThis.

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.install
- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_upsell/fundraiser_upsell.module
Adds a "Status" field to the fundraiser recurring series entity which can be mapped and synced to custom field in .
New series get a status of 'active'. When the final active donation in a series is updated, the series status is updated to reflect the appropriate status based on the $donation->status value of the last recurring donation.
> 7.x 4.x 1529 fundriaser recurring status

- fundraiser/modules/fundraiser_sustainers/fundraiser_sustainers.module
- fundraiser/modules/fundraiser_sustainers/includes/fundraiser_sustainers.views_default.inc
Adds a batch operation to set a donation to payment received.
Adds a batch_operation flag on the donation object prior to calling fundraiser_donation_success() when the batch operation is used.
> 7.x 4.x 1713 unlock sustainers payment received

- springboard_group/includes/springboard_group.fundraiser.inc
check for presence of og_group_ref_* before getting its value in springboard_group_fundraiser_offline_access()
> Fix fatals when entities such as donation forms don't have a og_group_ref_* field
